name: ecommerceApp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http:
  material_design_icons_flutter: ^4.0.5345
  stacked:
  flutter_svg: ^0.17.4 
  google_fonts:
  get_it:
  provider:
  photo_view:
  flutter_swiper: ^1.1.6
  animations: ^1.1.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_spinkit: "^4.1.2"
  flutter_facebook_login:
  cloud_firestore: ^0.13.6
  path_provider:
  sqflite: ^1.3.1
  cached_network_image:
  firebase_messaging: ^6.0.16
  bubble_tab_indicator: ^0.1.4
  flutter_rating_bar: ^3.0.1+1
  sembast:
  firebase_remote_config:
  package_info:
  flutter_html: ^1.0.0
  pull_to_refresh:
  flutter_typeahead: ^1.8.3
  intl_phone_number_input: ^0.4.6+2
  shared_preferences: ^0.5.7+3
 # flutter_staggered_grid_view: "^0.2.7"
  fluttertoast: ^4.0.1
  intl:
  async:
  stripe_payment: ^1.0.7
  flutter_credit_card: ^0.1.3
  http_auth:
  simple_animations:
  flutter_wordpress: ^0.2.1
  flutter_local_notifications: ^0.8.4+2
  url_launcher: ^5.1.2
  flutter_ringtone_player: ^2.0.0
  flutter_widget_from_html_core: ^0.4.1
  dio:
  dio_http_cache:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/geo.json
      - assets/curr.json
      - lang/en.json
      - lang/ar.json

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: MyFlutterApp
      fonts:
           - asset: fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
